### ISSUE TITLE
Detect accept headers better for xml/json

### ISSUE THREAD

**Issue by jchannon** [jchannon/negotiator#1]
Currently it checks if a string ends with xml/json on the header to determine if it will process the response.  This is poor. I think there is a library out there that already works all this out, I think it even uses the weight value in the Accept header as well. Probably best to use that lib.

**Comment by philcleveland** [comment]
Check this out. I didn't realize that the Accept header was this complicated.
https://bitbucket.org/ww/goautoneg/src/75cd24fc2f2c?at=default
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by jchannon** [comment]
Yeah autoneg was the one I was thinking of :+1:

**Comment by jchannon** [comment]
Not sure we can use this - https://bitbucket.org/ww/goautoneg/issues/1/incomplete-support-for-http-spec

**Comment by Yantrio** [comment]
there is also the case of multiple values passed into the accept header, which would it pick if any.

**Comment by jchannon** [comment]
Yeah. I'd expect something to handle that. I think Phil is going to see how
Nancy does it

**Comment by philcleveland** [comment]
Here is what I currently have in progress.  I think it is pretty close(at least from an "It works" perspective). Not sure how else to share with you guys outside of PR. @jchannon thanks for heads up on github.com/stretchr/testify/assert. I like using it. I was it in your testing PR.

https://github.com/pdoh00/negotiator/tree/AcceptHeaderNegotiation

**Comment by jchannon** [comment]
Wow! Nice work

**Comment by jchannon** [comment]
I think this is where Nancy deals with working out in what order to loop over the available processors. Basically looks at the Accept header, parses them, like your code does, orders the processor by `;q=1` in Accept header and then loops over them and calls `Process` https://github.com/NancyFx/Nancy/blob/45860c82e4df8e2d380997ddf1d19d61400fb145/src/Nancy/Responses/Negotiation/DefaultResponseNegotiator.cs

**Comment by jchannon** [comment]
@pdoh00 stick that in as a PR

**Comment by philcleveland** [comment]
@jchannon I definitely used the Nancy code as inspiration. It was pretty understandable.  In addition I used http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html. Currently all the Accept does is provide prioritized Media Ranges. I think it would be good to keep it basically doing that.  The negotiator can loop through the media ranges and make a decision on the processor.  With that said there is some matching logic needed for media ranges like "_/_", "type/_".  For "_/_" I think the Negotiate can just use the first processor. For "type/_" we will need to loop until finding the first processor with type.
