### ISSUE TITLE
File naming conventions

### ISSUE THREAD

**Issue by philcleveland** [jchannon/negotiator#6]
I think idiomatic go uses lower snake case for files. Check out source code at https://github.com/golang/go

**Comment by jchannon** [comment]
Are you using atom. That will give warnings on that. I don't get any

**Comment by jchannon** [comment]
Unless it only warns about struxt names

**Comment by philcleveland** [comment]
I am using atom, but have a :heavy_check_mark: No Issues. Where does the warning appear for you?

**Comment by jchannon** [comment]
When there's an issue it gives you warning at bottom on save

**Comment by philcleveland** [comment]
No issues for me regarding file naming.  Wonder if this is a setting difference.

![image](https://cloud.githubusercontent.com/assets/2169872/11126098/38665bbe-8922-11e5-9b78-7602296bcf4f.png)

**Comment by jchannon** [comment]
Sorry. That's what I'm saying. I don't get errors for file names. Should we?

**Comment by philcleveland** [comment]
I see. That could be a limitation of the tooling. With that in mind. I can't find anything specifically regarding file naming conventions in Go. I am only going off of what I see in the golang source code. I don't really mind if we use upper case, but think it best to at least be consistent across files

**Comment by jchannon** [comment]
Agreed

**Comment by jchannon** [comment]
see #8
